# Generated by Django 2.2.12 on 2020-04-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsGradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.CoursesModel', to_field='courses_code')),
                ('lecturer_nidn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.LecturerModel', to_field='lecturer_nidn')),
                ('student_nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.StudentModel', to_field='student_nim')),
            ],
            options={
                'db_table': 'student_grade',
            },
        ),
    ]
