# Generated by Django 2.2.12 on 2020-04-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_studentsgrademodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgrademodel',
            name='student_grade',
            field=models.FloatField(null=True),
        ),
    ]
